#!/usr/bin/env python

import numpy as np
import argparse
import os, sys

parser = argparse.ArgumentParser()

parser.add_argument('-v', "--value", help="value", type=float, default=1.0)
parser.add_argument('-o', "--output", help="output file")

args = parser.parse_args()

if args.value == None:
    parser.print_help()
    exit(1)

scale = args.value * np.ones(1, dtype=np.float32)
scale_array = (float(args.value) * np.ones((64, 64))).astype(dtype=np.float32)
header = np.frombuffer(buffer=b'NUCD', count=4, dtype=np.uint8)

if args.output:
    with open(args.output, "+wb") as f:
        f.truncate(0)
        f.write(header.tobytes())
        f.write(scale.tobytes())
        f.write(scale_array.tobytes())
        exit(0)

else:
    
    os.write(sys.stdout.fileno(), header.tobytes())
    os.write(sys.stdout.fileno(), scale.tobytes())
    os.write(sys.stdout.fileno(), scale_array.tobytes())
    
    
    exit(0)