#!/usr/bin/env python

import numpy as np
import argparse
import os, sys

parser = argparse.ArgumentParser()

parser.add_argument('-t', "--type", help="input type", default="float")
parser.add_argument('-i', "--input", help="input file", default="/mnt/mmc/sys/table_fw.nuc")
parser.add_argument('-o', "--output", help="output file", default="/etc/clamir/scc_core_scale_default.dat")

args = parser.parse_args()

if args.type:
    if args.type == "float":
        args.type = np.float32
    else:
        parser.print_help("Type is not supported ", args.type)
        exit(1)

try:
    _ = os.stat(args.input)

    input = np.fromfile(args.input, dtype=args.type)

    # Offset - 
    # offset = float(input[1])
    # scale = input[2:]
    scale = float(input[1])
    table = input[2:]

    
    scale_output = (scale * table).astype(dtype=np.int32)

    # offset_output = (offset * np.ones((64,64))).astype(dtype=np.int32)

    with open('scc_core_scale_default.dat', "wb") as f:
        # os.write('scc_core_scale_default.dat', scale_output)
        scale_output.tofile(f)

    # with open('scc_core_offset_default.dat', "+wb") as f:
        # os.write('scc_core_offset_default.dat', offset_output)
        # offset_output.tofile(f)

except Exception as e:
    parser.print_help("Failed to parse input file. {}", e)
    exit(1)